"""
Core system constants, city baselines, and POI taxonomies for BusOS.
Single Source of Truth (SSOT).
"""

CITY_BASELINES = {
    "warszawa": 1800000,
    "krakow": 800000,
    "lodz": 670000,
    "wroclaw": 640000,
    "poznan": 530000,
    "szczecin": 400000,
    "bydgoszcz": 340000,
    "lublin": 330000,
    "bialystok": 290000,
    "katowice": 290000,
    "gzm": 2300000,
    "rzeszow": 190000,
    "kielce": 190000,
    "olsztyn": 170000,
    "radom": 200000,
    "torun": 190000,
    "czestochowa": 210000,
    "legnica": 90000,
    "elblag": 110000,
    "opole": 120000,
    "gorzow": 120000,
    "suwalki": 70000,
    "elk": 60000,
    "lomza": 60000,
    "przemysl": 60000,
    "gizycko": 30000,
    "swinoujscie": 40000,
}

TAG_WHITELIST = {
    "aerodrome": "international_airport",
    "terminal": "airport_terminal",
    "port": "major_seaport",
    "station": "rail_hub",
    "university": "university_campus",
    "college": "university_campus",
    "faculty": "university_campus",
    "stadium": "national_stadium",
    "arena": "national_stadium",
    "exhibition_centre": "exhibition_centre",
    "hospital": "hospital_clinical",
    "mall": "shopping_mall",
    "shopping_centre": "shopping_mall",
    "department_store": "shopping_mall",
    "office": "business_office",
    "company": "business_office",
    "industrial": "industrial_zone",
    "commercial": "commercial_zone",
    "warehouse": "logistics_hub",
    "courthouse": "government_central",
    "court_house": "government_central",
    "townhall": "government_central",
    "government": "government_central",
    "supermarket": "supermarket",
    "student_accommodation": "student_dormitory",
    "dormitory": "student_dormitory",
    "school": "education_high_school",
    "marketplace": "marketplace",
    "social_facility": "social_support_mops",
    "clinic": "health_clinic",
    "doctors": "health_clinic",
    "dentist": "health_clinic",
    "theatre": "culture_theatre",
    "cinema": "culture_theatre",
    "museum": "culture_theatre",
    "library": "culture_theatre",
    "sports_hall": "sports_centre",
    "sports_centre": "sports_centre",
    "swimming_pool": "sports_centre",
    "kindergarten": "education_preschool",
    "pharmacy": "pharmacy",
    "bank": "bank",
    "post_office": "post_office",
    "police": "police_station",
    "convenience": "convenience_store",
    "place_of_worship": "place_of_worship",
    "park": "park_recreation",
    "garden": "park_recreation",
    "hotel": "hotel_accommodation",
    "hostel": "hotel_accommodation",
    "clothes": "specialized_retail",
    "furniture": "specialized_retail",
    "electronics": "specialized_retail",
    "fuel": "car_services",
    "car_repair": "car_services",
    "restaurant": "gastronomy",
    "cafe": "gastronomy",
    "fast_food": "gastronomy",
    "beauty": "personal_services",
    "hairdresser": "personal_services",
    "chemist": "personal_services",
    "airfield": "local_airfield",
    "parcel_locker": "micro_parcel_locker",
    "atm": "micro_atm",
    "playground": "micro_playground",
}

TIER_POINTS = {
    "T0_MEGA_HUB": 5000000,
    "T1_NATIONAL_MAGNET": 1000000,
    "T2_STRATEGIC_HUB": 250000,
    "T3_LOCAL_CORE": 50000,
    "T4_DAILY_SERVICE": 10000,
    "T5_SPEC_GASTRO": 2500,
    "T6_MICRO_INFRA": 100,
}
